spring:
  data.mongodb:
    host: localhost
    port: 27017
    username: root
    password: example
    database: local
    authentication-database: admin
  cache.type: redis
  redis:
    host: localhost
    port: 6379